plugins:
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false
